- name: Create the docker group
  group: name=docker gid=993

- name: Create the operation group
  group: name=operation gid=1000

- name: Create the deployer user
  user: user=deployer group=operation groups=docker

- name: Copy docker file to all the node
  copy: src={{ docker_binary_dir }}/{{ item }} dest=/usr/bin/{{ item }} owner=root group=operation mode=0755
  with_items:
  - docker
  - docker-containerd
  - docker-containerd-ctr
  - docker-containerd-shim
  - dockerd
  - docker-init
  - docker-proxy
  - docker-runc

- name: Copy docker service file
  copy: src=docker.service dest=/usr/lib/systemd/system/docker.service

- name: Create docker configuration directory
  file: name=/etc/docker/certs.d/{{ docker_domain }} owner=root group=root state=directory recurse=true

- name: Create configuration file for docker
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json

- name: Copy the ca files for docker
  copy: src=ca.crt dest=/etc/docker/certs.d/{{ docker_domain }}/ca.crt mode=0644

- name: Reload docker service
  command: systemctl daemon-reload

- name: Start docker service
  service: name=docker enabled=yes state=started

- name: Change the iptables rule
  command: "iptables -P FORWARD ACCEPT"
